# Site settings
#theme
theme: jekyll-theme-slate

#Site basics
title: "Under the Hood: Adventures in Security Research"
description: "Exploring malware, vulnerabilities, and reverse engineering software to find out how it really works."
url: "https://mja-reversing.github.io"
baseurl: "/Under-the-Hood-Adventures-in-Security-Research"

# Author Info
author:
  name: "Matt Allan"
  bio: "Security researcher who analyzes malware by day and (tries) to find vulnerabilities by night."

# Navigation
navbar:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about"
  - title: "Blog"
    url: "/blog"

# Markdown & Syntax Highlighting
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Blog Post Settings
permalink: /:categories/:title/
paginate: 5
paginate_path: "/page:num/"

# Collections (lets you expand later)
collections:
  notes:
    output: true
    permalink: /notes/:path/

# Defaults (auto-apply layouts)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Plugins supported by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclusions (files not published)
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
